# Generated by Django 2.1.3 on 2018-11-27 01:03

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30)),
                ('Delivered', models.NullBooleanField(default=False)),
                ('Status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('TERMINADO', 'TERMINADO'), ('CANCELADO', 'CANCELADO')], default='PENDIENTE', max_length=11)),
                ('OrderDate', models.DateTimeField()),
                ('DeliveryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersApp.ClientOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
                ('ProductionCost', models.FloatField()),
                ('Image', imagekit.models.fields.ProcessedImageField(upload_to='ProductImages')),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersApp.Product'),
        ),
    ]
