# Generated by Django 2.1.3 on 2018-11-27 03:15

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='Delivered',
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='Status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('TERMINADO', 'TERMINADO'), ('CANCELADO', 'CANCELADO'), ('ENTREGADO', 'ENTREGADO')], default='PENDIENTE', max_length=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='ProductImages/'),
        ),
    ]
