# Generated by Django 2.1.3 on 2018-11-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_auto_20181126_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Description',
        ),
    ]
