# Generated by Django 2.1.3 on 2018-11-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0003_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
