# Generated by Django 2.1.3 on 2018-12-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0004_auto_20181128_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='Note',
            field=models.TextField(blank=True),
        ),
    ]
