# Generated by Django 2.1.3 on 2018-12-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0005_clientorder_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='DeliveryDate',
        ),
    ]
